version: "3.8"

volumes:
  postgres_data: { }

services:
  bot:
    env_file:
      - .env
    volumes:
      - ./admin_app/admin_panel/media:/workdir/media:rw
    build:
      context: bot_app
      dockerfile: bot.dockerfile
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    profiles:
      - full_run
    user: "1000"

  admin_app:
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - ./admin_app/admin_panel/staticfiles:/workdir/staticfiles
      - ./admin_app/admin_panel/media:/workdir/media:rw
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    build:
      context: ./admin_app
      dockerfile: admin.dockerfile
    depends_on:
      - postgres
    profiles:
      - full_run
    user: "1000"

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    ports:
      - "5432:5432"
    profiles:
      - full_run
      - local_dev

  proxy:
    image: nginx
    ports:
      - "1337:80"
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    depends_on:
      - admin_app
    volumes:
      - ./admin_app/admin_panel/staticfiles:/workdir/staticfiles:ro
      - ./admin_app/admin_panel/media:/workdir/media:rw
    profiles:
      - full_run
