version: "3.8"

volumes:
  postgres_data: { }

services:
  admin_app:
    volumes:
      - ./admin_app/admin_panel/media:/workdir/media:rw
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    build:
      context: ./admin_app
      dockerfile: admin.dockerfile
    depends_on:
      - postgres
    profiles:
      - full_run
    ports:
      - "8080:8080"
    user: "1000"

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    ports:
      - "5432:5432"
    profiles:
      - full_run
      - local_dev
